<?php

namespace Tests\Feature\Controller;

// use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Models\Product;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Laravel\Passport\Passport;
use Tests\TestCase;

class CartItemControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * A basic test example.
     */

    private $fakeUser;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->fakeUser = User::create([
            'email' => 'test@test.com',
            'name' => 'testing',
            'password' => 123456789
        ]);
        Passport::actingAs($this->fakeUser);
    }

    public function testStore()
    {
        $cart = $this->fakeUser->carts()->create();
        $product = Product::create([
            'title' => 'test Product',
            'content' => 'cool',
            'price' => 10,
            'quantity' => 10
        ]);
        $response = $this->call(
            'POST',
            'cart-items',
            ['cart_id' => $cart->id, 'product_id' => $product->id, 'quantity' => 2]
        );
        $response->assertOk();

        $response = $this->call(
            'POST',
            'cart-items',
            ['cart_id' => $cart->id, 'product_id' => $product->id, 'quantity' => 999]
        );
        $response->assertStatus(400);
    }
}
